// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ssis.Data;

#nullable disable

namespace ssis.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ssis.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("BookId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            BookName = "Basic technical mathematics with calculus",
                            SubjectId = 1
                        },
                        new
                        {
                            BookId = 2,
                            BookName = "Essential Maths",
                            SubjectId = 1
                        },
                        new
                        {
                            BookId = 3,
                            BookName = "The Great Gatsby",
                            SubjectId = 2
                        },
                        new
                        {
                            BookId = 4,
                            BookName = "To Kill A Mockingbird",
                            SubjectId = 2
                        },
                        new
                        {
                            BookId = 5,
                            BookName = "The Story Of Art",
                            SubjectId = 3
                        },
                        new
                        {
                            BookId = 6,
                            BookName = "501 Essential French Verbs",
                            SubjectId = 4
                        },
                        new
                        {
                            BookId = 7,
                            BookName = "Organic Chemistry",
                            SubjectId = 5
                        });
                });

            modelBuilder.Entity("ssis.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfWeeklyClasses")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Basic Math",
                            Name = "Math",
                            NumberOfWeeklyClasses = 5
                        },
                        new
                        {
                            Id = 2,
                            Description = "Basic English",
                            Name = "English",
                            NumberOfWeeklyClasses = 4
                        },
                        new
                        {
                            Id = 3,
                            Description = "Basic Art",
                            Name = "Art",
                            NumberOfWeeklyClasses = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Begginer French",
                            Name = "French",
                            NumberOfWeeklyClasses = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Basic Chemistry",
                            Name = "Chemistry",
                            NumberOfWeeklyClasses = 5
                        });
                });

            modelBuilder.Entity("ssis.Models.Book", b =>
                {
                    b.HasOne("ssis.Models.Subject", "Subject")
                        .WithMany("LiteratureUsed")
                        .HasForeignKey("SubjectId");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ssis.Models.Subject", b =>
                {
                    b.Navigation("LiteratureUsed");
                });
#pragma warning restore 612, 618
        }
    }
}
